server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/productdb
    username: root
    password: generic
  application:
    name: product-service
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.MySQLDialect 
    